import type { MenuContent } from "@/lib/types";

/**
 * Sample content for the first client. Components never hardcode this café —
 * they only read MenuContent. Duplicate the repo, change this seed (or Studio
 * / Sanity), and the live site is a new café.
 */
export const SEED_MENU: MenuContent = {
  settings: {
    _id: "restaurantSettings",
    _type: "restaurantSettings",
    name: "The Hashtag Cafe",
    tagline: "All-day café · Nagole, Hyderabad",
    logo: "/logo.svg",
    whatsappNumber: "917997111179",
    address:
      "3-76-B, New Nagole Main Rd, Maa Residency, New Nagole Colony, Kothapet, Hyderabad, Telangana 500035",
    googleMapsUrl: "https://maps.app.goo.gl/C5mkC752EMzRa5Nk7?g_st=ic",
    hours: "11:30 AM – 11:00 PM · Open all week",
  },
  categories: [
    { _id: "cat-pizza", _type: "menuCategory", title: "Pizza", slug: "pizza", order: 1 },
    { _id: "cat-sandwiches", _type: "menuCategory", title: "Sandwiches", slug: "sandwiches", order: 2 },
    { _id: "cat-burgers", _type: "menuCategory", title: "Burgers", slug: "burgers", order: 3 },
    { _id: "cat-mexican", _type: "menuCategory", title: "Mexican", slug: "mexican", order: 4 },
    { _id: "cat-chinese", _type: "menuCategory", title: "Chinese", slug: "chinese", order: 5 },
    { _id: "cat-desserts", _type: "menuCategory", title: "Desserts", slug: "desserts", order: 6 },
    { _id: "cat-beverages", _type: "menuCategory", title: "Beverages", slug: "beverages", order: 7 },
  ],
  items: [
    {
      _id: "item-margherita",
      _type: "menuItem",
      name: "Margherita",
      slug: "margherita",
      categoryId: "cat-pizza",
      price: 249,
      description: "San Marzano tomato, mozzarella, basil, olive oil.",
      dietType: "veg",
      image: "/menu/margherita.jpg",
      available: true,
      featured: false,
      order: 1,
    },
    {
      _id: "item-paneer-tikka-pizza",
      _type: "menuItem",
      name: "Paneer Tikka Pizza",
      slug: "paneer-tikka-pizza",
      categoryId: "cat-pizza",
      price: 329,
      description: "Tandoori paneer, peppers, onion, mint mayo.",
      dietType: "veg",
      image: "/menu/paneer-tikka-pizza.jpg",
      available: true,
      featured: true,
      order: 2,
    },
    {
      _id: "item-farmhouse",
      _type: "menuItem",
      name: "Farmhouse",
      slug: "farmhouse",
      categoryId: "cat-pizza",
      price: 299,
      description: "Mushroom, capsicum, tomato, onion, mozzarella.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 3,
    },
    {
      _id: "item-bbq-chicken-pizza",
      _type: "menuItem",
      name: "BBQ Chicken Pizza",
      slug: "bbq-chicken-pizza",
      categoryId: "cat-pizza",
      price: 369,
      description: "Smoked chicken, BBQ glaze, red onion, mozzarella.",
      dietType: "nonveg",
      image: "/menu/bbq-chicken-pizza.jpg",
      available: true,
      featured: true,
      order: 4,
    },
    {
      _id: "item-corn-cheese",
      _type: "menuItem",
      name: "Corn Cheese",
      slug: "corn-cheese",
      categoryId: "cat-pizza",
      price: 279,
      description: "Sweet corn, extra cheese, oregano.",
      dietType: "veg",
      available: false,
      featured: false,
      order: 5,
    },
    {
      _id: "item-veg-club",
      _type: "menuItem",
      name: "Classic Veg Club",
      slug: "classic-veg-club",
      categoryId: "cat-sandwiches",
      price: 189,
      description: "Triple-layer toasted sandwich with cheese and slaw.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 1,
    },
    {
      _id: "item-paneer-sandwich",
      _type: "menuItem",
      name: "Paneer Tikka Sandwich",
      slug: "paneer-tikka-sandwich",
      categoryId: "cat-sandwiches",
      price: 209,
      description: "Grilled paneer tikka, onion, mint chutney.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 2,
    },
    {
      _id: "item-garlic-toast",
      _type: "menuItem",
      name: "Cheese Garlic Toast",
      slug: "cheese-garlic-toast",
      categoryId: "cat-sandwiches",
      price: 159,
      description: "Pull-apart garlic bread, mozzarella, parsley.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 3,
    },
    {
      _id: "item-chicken-sandwich",
      _type: "menuItem",
      name: "Grilled Chicken Sandwich",
      slug: "grilled-chicken-sandwich",
      categoryId: "cat-sandwiches",
      price: 229,
      description: "Char-grilled chicken, lettuce, chipotle mayo.",
      dietType: "nonveg",
      available: true,
      featured: false,
      order: 4,
    },
    {
      _id: "item-veg-burger",
      _type: "menuItem",
      name: "Veg Patty Burger",
      slug: "veg-patty-burger",
      categoryId: "cat-burgers",
      price: 189,
      description: "Crisp vegetable patty, cheese, house sauce.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 1,
    },
    {
      _id: "item-cheese-burger",
      _type: "menuItem",
      name: "Cheese Burger",
      slug: "cheese-burger",
      categoryId: "cat-burgers",
      price: 199,
      description: "Double cheese, pickle, toasted bun.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 2,
    },
    {
      _id: "item-fried-chicken-burger",
      _type: "menuItem",
      name: "Fried Chicken Burger",
      slug: "fried-chicken-burger",
      categoryId: "cat-burgers",
      price: 249,
      description: "Crispy fried chicken, slaw, spicy mayo.",
      dietType: "nonveg",
      image: "/menu/fried-chicken-burger.jpg",
      available: true,
      featured: true,
      order: 3,
    },
    {
      _id: "item-minced-chicken-burger",
      _type: "menuItem",
      name: "Minced Chicken Burger",
      slug: "minced-chicken-burger",
      categoryId: "cat-burgers",
      price: 249,
      description: "Grilled chicken patty, cheddar, caramelised onion.",
      dietType: "nonveg",
      available: true,
      featured: false,
      order: 4,
    },
    {
      _id: "item-veg-quesadilla",
      _type: "menuItem",
      name: "Veg Quesadilla",
      slug: "veg-quesadilla",
      categoryId: "cat-mexican",
      price: 229,
      description: "Peppers, corn, cheese, salsa, sour cream.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 1,
    },
    {
      _id: "item-chicken-quesadilla",
      _type: "menuItem",
      name: "Chicken Quesadilla",
      slug: "chicken-quesadilla",
      categoryId: "cat-mexican",
      price: 269,
      description: "Spiced chicken, cheddar, jalapeño.",
      dietType: "nonveg",
      available: true,
      featured: false,
      order: 2,
    },
    {
      _id: "item-loaded-nachos",
      _type: "menuItem",
      name: "Loaded Nachos",
      slug: "loaded-nachos",
      categoryId: "cat-mexican",
      price: 219,
      description: "Corn chips, cheese sauce, salsa, jalapeños.",
      dietType: "veg",
      image: "/menu/loaded-nachos.jpg",
      available: true,
      featured: true,
      order: 3,
    },
    {
      _id: "item-mexican-bowl",
      _type: "menuItem",
      name: "Mexican Rice Bowl",
      slug: "mexican-rice-bowl",
      categoryId: "cat-mexican",
      price: 249,
      description: "Cilantro rice, beans, pico, guacamole.",
      dietType: "vegan",
      available: true,
      featured: false,
      order: 4,
    },
    {
      _id: "item-veg-manchurian",
      _type: "menuItem",
      name: "Veg Manchurian",
      slug: "veg-manchurian",
      categoryId: "cat-chinese",
      price: 199,
      description: "Crisp vegetable balls in hot garlic sauce.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 1,
    },
    {
      _id: "item-hakka",
      _type: "menuItem",
      name: "Veg Hakka Noodles",
      slug: "veg-hakka-noodles",
      categoryId: "cat-chinese",
      price: 189,
      description: "Wok-tossed noodles, cabbage, carrot, pepper.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 2,
    },
    {
      _id: "item-chilli-chicken",
      _type: "menuItem",
      name: "Chilli Chicken",
      slug: "chilli-chicken",
      categoryId: "cat-chinese",
      price: 249,
      description: "Boneless chicken, dry chilli, spring onion.",
      dietType: "nonveg",
      image: "/menu/chilli-chicken.jpg",
      available: true,
      featured: true,
      order: 3,
    },
    {
      _id: "item-chicken-fried-rice",
      _type: "menuItem",
      name: "Chicken Fried Rice",
      slug: "chicken-fried-rice",
      categoryId: "cat-chinese",
      price: 219,
      description: "Egg-fried rice, chicken, soy, spring onion.",
      dietType: "nonveg",
      available: true,
      featured: false,
      order: 4,
    },
    {
      _id: "item-egg-fried-rice",
      _type: "menuItem",
      name: "Egg Fried Rice",
      slug: "egg-fried-rice",
      categoryId: "cat-chinese",
      price: 199,
      description: "Wok rice, scrambled egg, spring onion.",
      dietType: "egg",
      available: true,
      featured: false,
      order: 5,
    },
    {
      _id: "item-brownie",
      _type: "menuItem",
      name: "Chocolate Brownie",
      slug: "chocolate-brownie",
      categoryId: "cat-desserts",
      price: 149,
      description: "Warm walnut brownie, chocolate sauce.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 1,
    },
    {
      _id: "item-nutella-waffle",
      _type: "menuItem",
      name: "Nutella Waffle",
      slug: "nutella-waffle",
      categoryId: "cat-desserts",
      price: 189,
      description: "Belgian waffle, Nutella, roasted hazelnut.",
      dietType: "veg",
      image: "/menu/nutella-waffle.jpg",
      available: true,
      featured: true,
      order: 2,
    },
    {
      _id: "item-cheesecake",
      _type: "menuItem",
      name: "Gulab Jamun Cheesecake",
      slug: "gulab-jamun-cheesecake",
      categoryId: "cat-desserts",
      price: 169,
      description: "Baked cheesecake, gulab jamun, pistachio.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 3,
    },
    {
      _id: "item-sizzling-brownie",
      _type: "menuItem",
      name: "Sizzling Brownie",
      slug: "sizzling-brownie",
      categoryId: "cat-desserts",
      price: 219,
      description: "Brownie on a hot plate, ice cream, chocolate.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 4,
    },
    {
      _id: "item-masala-chai",
      _type: "menuItem",
      name: "Masala Chai",
      slug: "masala-chai",
      categoryId: "cat-beverages",
      price: 59,
      description: "Ginger-cardamom chai, full boil.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 1,
    },
    {
      _id: "item-lime-soda",
      _type: "menuItem",
      name: "Fresh Lime Soda",
      slug: "fresh-lime-soda",
      categoryId: "cat-beverages",
      price: 89,
      description: "Sweet, salt, or mixed. Ask your server.",
      dietType: "vegan",
      available: true,
      featured: false,
      order: 2,
    },
    {
      _id: "item-americano",
      _type: "menuItem",
      name: "Iced Americano",
      slug: "iced-americano",
      categoryId: "cat-beverages",
      price: 129,
      description: "Double shot over ice.",
      dietType: "vegan",
      available: true,
      featured: false,
      order: 3,
    },
    {
      _id: "item-cold-coffee",
      _type: "menuItem",
      name: "Classic Cold Coffee",
      slug: "classic-cold-coffee",
      categoryId: "cat-beverages",
      price: 149,
      description: "Blended espresso, milk, ice cream float.",
      dietType: "veg",
      image: "/menu/cold-coffee.jpg",
      available: true,
      featured: true,
      order: 4,
    },
    {
      _id: "item-kitkat-shake",
      _type: "menuItem",
      name: "KitKat Thickshake",
      slug: "kitkat-thickshake",
      categoryId: "cat-beverages",
      price: 189,
      description: "Crushed KitKat, chocolate ice cream.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 5,
    },
    {
      _id: "item-mango-shake",
      _type: "menuItem",
      name: "Mango Thickshake",
      slug: "mango-thickshake",
      categoryId: "cat-beverages",
      price: 169,
      description: "Alphonso pulp, vanilla ice cream.",
      dietType: "veg",
      available: true,
      featured: false,
      order: 6,
    },
  ],
};
